### ISSUE TITLE
Request for Open Source License

### ISSUE THREAD

**Issue by brooklynsheppard** [ellamguest/online-misogyny-eacl2021#1]
Hi there,

I am a Machine Learning Developer in Mila's AI for Humanity department working on the Biasly project. In our work, we came across your paper "An expert annotated dataset for the detection of online misogyny" and found it very useful for our project!

We are hoping to use the dataset published on this Github repository for some of our experiments, but are unable to as, as far as we could see, the Github repository does not contain an open source license. 

We were therefore wondering if you would be willing to [add an open source license to the repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) so that we can use this dataset for our project?

Please let us know if you'd like to learn more about our project or need additional information regarding licensing the dataset.

Best,

Brooklyn and the Biasly team

**Comment by ellamguest** [comment]
Added an MIT license. Best of luck with the project and let me know if you have any questions!
